version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6380:6379'
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_DB=eatwithmax
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eatwithmax
    ports:
      - '5433:5432'
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh docker-start.sh
    depends_on:
      - 'postgres'
      - 'redis'
    ports:
      - '3000:3000'
    working_dir: /usr/eatwithmax
    volumes:
      - .:/usr/eatwithmax:cached
      - /usr/eatwithmax/node_modules
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:eatwithmax@postgres:5432/eatwithmax
      - REDIS_URL=redis://redis:6379
      - WAIT_HOSTS=postgres:5432, redis:6379
