version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6380:6379'
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_DB=maxandfood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxandfood
    ports:
      - '5433:5432'
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - 'postgres'
      - 'redis'
    ports:
      - '3000:3000'
    working_dir: /usr/maxandfood
    volumes:
      - .:/usr/maxandfood:cached
      - /usr/maxandfood/node_modules
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:maxandfood@postgres:5432/maxandfood
      - REDIS_URL=redis://redis:6379
      - WAIT_HOSTS=postgres:5432, redis:6379
